[package]
name = "dripp_backend"
version = "1.0.0"
edition = "2018"
authors = ["Anirudh Vyas <ricky.nj@gmail.com>"]
description = "Iroh based FFI library to build fllutter based app Dripp"
license = "MIT"
repository = "https://github.com/goldilocksfashion/dripp_backend"
documentation = "https://docs.rs/dripp_backend"
homepage = "https://dripp.app"
keywords = ["p2p", "ffi", "networking", "social", "flutter", "dripp"]
categories = ["network-programming", "data-structures", "social-networking", "flutter", "peer-to-peer"]

[lib]
name = "dripp_backend"
crate-type = ["staticlib", "cdylib"]

[dependencies]
## Core
flutter_rust_bridge = "2.7.0"
derive_builder = "0.20.2"
thiserror = "2.0.11"
yrs = "0.22.0"
tokio = { version = "1.10.0", features = ["rt", "rt-multi-thread", "io-util", "time", "sync"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio", "macros", "sqlite", "json", "uuid", "tls-native-tls"] }
serde =  "1.0.217" 
serde_json = "1.0.137"
iroh = "0.31.0"
futures = "0.3"
once_cell = "1.0"


## Optional
tracing = { version = "0.1", optional = true }

[dev-dependencies]
proptest = "1.6.0" 

[profile.release]
strip = "symbols" # Strip unnecessary symbols during build
opt-level = "z" 
lto = true
panic = "abort" # Abort on panic