aws codeartifact publish-package-version \
    --domain goldilocksfashion \
    --domain-owner 730335644490 \
    --repository dripp-ai-infrastructure \
    --format pypi \
    --namespace dripp-ai \
    --package dripp_events \
    --package-version 0.1 \
    --asset dist \
    --asset-name dripp_events-0.1.tar.gz \
    --asset-hash $(sha256sum dist/dripp_events-0.1.tar.gz | awk '{print $1}') \
    --asset-hash-algorithm sha256