[pytest]
addopts = --ignore=lib/python3.12/site-packages/asyncio
          --ignore=lib/python3.12/site-packages/sniffio
          --ignore=lib/python3.12/site-packages/trio
          --ignore=lib/python3.12/site-packages/confluent_kafka
          --ignore=lib/python3.12/site-packages/pytest
